platform :osx, '12.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

flutter_root = File.expand_path(File.join('..', 'Flutter'), __dir__)
require File.join(flutter_root, 'podhelper')

flutter_macos_podfile_setup

target 'Runner' do
  flutter_install_all_macos_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  flutter_additional_macos_build_settings(installer)
end


