platform :ios, '13.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

flutter_root = File.expand_path(File.join('..', 'Flutter'), __dir__)
require File.join(flutter_root, 'podhelper')

flutter_ios_podfile_setup

target 'Runner' do
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  flutter_additional_ios_build_settings(installer)
end

